services:
  postgres:
    image: postgres:16
    container_name: crypto-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cryptobot
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cryptobot"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: crypto-app
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8081:8081"
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: crypto-swagger
    ports:
      - "8082:8080"
    environment:
      SWAGGER_JSON: /openapi.yaml
    volumes:
      - ./docs/openapi.yaml:/openapi.yaml