name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main


jobs:
  test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4


      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"


      - name: Download dependencies
        run: go mod download


      - name: Tests
        run: go test ./...


      - name: Build
        run: go build ./...
      
      
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/cryptobot
            git pull
            docker compose up -d --build


      - name: Lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: latest